version: '3'
services:
  redis:
      image: redis:5
      ports:
        - "6379:6379"

# services:
#   node-app:
#     build: .
#     image: node-app
#     environment:
#       - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
#     ports:
#       - '3000:3000'
#     depends_on:
#       - mongodb
#     volumes:
#       - .:/usr/src/node-app
#     networks:
#       - node-network

#   mongodb:
#     image: mongo:4.2.1-bionic
#     ports:
#       - '27017:27017'
#     volumes:
#       - dbdata:/data/db
#     networks:
#       - node-network

# # Later add the node-network to the redis client
#   redis:
#     image: redis:5
#     ports:
#       - "127.0.0.1:6379:6379"
#     networks:
#       - node-network
# volumes:
#   dbdata:

# networks:
#   node-network:
#     driver: bridge
